name:                lambda-terminal
version:             0.1.0.0
github:              "gaborcs/lambda-terminal"
license:             BSD3
author:              "Gabor Csizmadia"
maintainer:          "gaborcsiz@gmail.com"
copyright:           "2018 Gabor Csizmadia"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gaborcs/lambda-terminal#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- containers
- deepseq
- hspec
- lens
- mtl
- safe
- text-zipper
- vector
- vty

library:
  source-dirs: src

executables:
  lambda-terminal-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-terminal

tests:
  lambda-terminal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-terminal
